name: functions-deployment-template

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: '.'

jobs:
  apply:
    env:
      # @devsupply token
      NPM_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
      # @nfcc-functions token
      NFCC_NPM_TOKEN: ${{ secrets.NFCC_NPM_TOKEN }}

      #AWS specific settings
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Azure specific settings
      # ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      # ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      # ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      # ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      # ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/setup-node@v1

      - run: npm install

      - name: Terraform Apply
        id: init
        run: node ./node_modules/.bin/functions-bundler apply --auto-approve
